### ISSUE TITLE
[ENVIRONMENT] 개발 환경 설정

### ISSUE THREAD

**Issue by marshot9420** [marshot9420/marstube#1]
### 🤔 Describe

기능 개발에 앞서 추가적인 환경 설정

### ✅ Tasks

- [ ] Express.js 설치
- [ ] Prettier 설정
- [ ] nodemon 설정
- [ ] Babel 설정
- [ ] Pug 설정
- [ ] Sass 설정
- [ ] Webpack 설정
- [ ] 환경 변수 추가
- [ ] morgan 및 winston 커스텀 로거 추가
- [ ] Success 인터셉터 추가
- [ ] Exception 핸들러 추가
